# permissions for end users to edit quaymirrorrepositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: quaymirrorrepository-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: quay-mirror-operator
    app.kubernetes.io/part-of: quay-mirror-operator
    app.kubernetes.io/managed-by: kustomize
  name: quaymirrorrepository-editor-role
rules:
- apiGroups:
  - clementperrin.fr
  resources:
  - quaymirrorrepositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - clementperrin.fr
  resources:
  - quaymirrorrepositories/status
  verbs:
  - get
