# permissions for end users to view quaymirrorlocations.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: quaymirrorlocation-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: quay-mirror-operator
    app.kubernetes.io/part-of: quay-mirror-operator
    app.kubernetes.io/managed-by: kustomize
  name: quaymirrorlocation-viewer-role
rules:
- apiGroups:
  - clementperrin.fr
  resources:
  - quaymirrorlocations
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - clementperrin.fr
  resources:
  - quaymirrorlocations/status
  verbs:
  - get
